---
- name: Deploy VLESS via NixOS on MelisStoke
  hosts: vless_hosts
  roles:
    # TODO: Not needed? Or just verify + change ssh key generation to use
    # invoke.
    # - role: bootstrap_prereqs
    #   tags: vless

    - role: bootstrap_ssh
      tags: vless

    # - role: bootstrap_clone
    #   tags: vless

    # - role: bootstrap_run
    #   tags: vless

    # - role: bootstrap_links
    #   tags: vless
