[local]
localhost
[local:vars]
ansible_connection=local

[windows]
virtual-machine-host
[windows:vars]
ansible_python_interpreter=J:\ds13\Soft\-scoop\apps\python\current\python.exe

[MelisStoke]
MelisStoke

[vless_hosts]
MelisStoke
